global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets:
          - localhost:9090

  - job_name: golang-app
    static_configs:
      - targets:
          - prometheus-golang:8000
